2021-06-18T14:28:50.9358821+08:00|1|INFO|DataSync.Log|Storage folder: D:\unity專案\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T14:28:50.9717863+08:00|116|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T14:28:51.0282167+08:00|116|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T14:28:51.0800524+08:00|116|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T14:28:51.1326565+08:00|116|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T14:29:20.9867864+08:00|116|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2021-06-18T14:29:21.0825302+08:00|116|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 75df80d9351d49a59829d116e17bc7c5(0-0). 
2021-06-18T14:29:21.0825302+08:00|116|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 75df80d9351d49a59829d116e17bc7c5(0-0). 
2021-06-18T14:29:42.2099566+08:00|120|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 75df80d9351d49a59829d116e17bc7c5(0-0). Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2021-06-18T14:29:42.2099566+08:00|120|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 75df80d9351d49a59829d116e17bc7c5(0-0). Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
2021-06-18T14:31:18.3386943+08:00|1|INFO|DataSync.Log|Storage folder: D:\unity專案\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T14:31:18.3716058+08:00|123|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T14:31:18.4254339+08:00|123|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T14:31:18.4767021+08:00|123|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T14:31:18.5305525+08:00|123|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T14:31:48.3866545+08:00|122|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2021-06-18T14:31:48.4510157+08:00|122|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 0a8dc59ed0094e348263f34c7907d442(0-0). 
2021-06-18T14:31:48.4510157+08:00|122|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 0a8dc59ed0094e348263f34c7907d442(0-0). 
2021-06-18T14:32:09.5468336+08:00|122|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 0a8dc59ed0094e348263f34c7907d442(0-0). Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2021-06-18T14:32:09.5498032+08:00|122|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 0a8dc59ed0094e348263f34c7907d442(0-0). Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
2021-06-18T14:33:58.3361199+08:00|1|INFO|DataSync.Log|Storage folder: D:\unity專案\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T14:33:58.3700007+08:00|148|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T14:33:58.4250595+08:00|148|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T14:33:58.4780568+08:00|148|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T14:33:58.5299985+08:00|148|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T14:42:25.4706339+08:00|1|INFO|DataSync.Log|Storage folder: D:\unity專案\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T14:42:25.5045133+08:00|195|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T14:42:25.5585267+08:00|195|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T14:42:25.6103900+08:00|195|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T14:42:25.6617643+08:00|195|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T14:42:55.5166063+08:00|196|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2021-06-18T14:42:55.5684675+08:00|196|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: b82e261de38c4e0694a96b07c4460b06(0-0). 
2021-06-18T14:42:55.5684675+08:00|196|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: b82e261de38c4e0694a96b07c4460b06(0-0). 
2021-06-18T14:43:16.6710795+08:00|199|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: b82e261de38c4e0694a96b07c4460b06(0-0). Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2021-06-18T14:43:16.6740723+08:00|199|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: b82e261de38c4e0694a96b07c4460b06(0-0). Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
2021-06-18T14:55:19.4454234+08:00|1|INFO|DataSync.Log|Storage folder: D:\unity專案\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T14:55:19.4793034+08:00|221|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T14:55:19.5343598+08:00|221|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T14:55:19.5859691+08:00|221|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T14:55:19.6378310+08:00|221|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T14:55:49.4905592+08:00|224|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2021-06-18T14:55:49.5444157+08:00|224|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 5e5b4260d21c47398c15dbf14fd34d0e(0-0). 
2021-06-18T14:55:49.5444157+08:00|224|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 5e5b4260d21c47398c15dbf14fd34d0e(0-0). 
2021-06-18T14:56:10.6386874+08:00|226|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 5e5b4260d21c47398c15dbf14fd34d0e(0-0). Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2021-06-18T14:56:10.6386874+08:00|226|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 5e5b4260d21c47398c15dbf14fd34d0e(0-0). Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
2021-06-18T14:58:45.3239832+08:00|1|INFO|DataSync.Log|Storage folder: D:\unity專案\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T14:58:45.3568647+08:00|245|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T14:58:45.4107618+08:00|245|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T14:58:45.4626102+08:00|245|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T14:58:45.5145118+08:00|245|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T14:59:15.3701161+08:00|245|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2021-06-18T14:59:15.4229745+08:00|245|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: d138cc0a0f7f4dc0b23b18ae94538f7f(0-0). 
2021-06-18T14:59:15.4249700+08:00|245|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: d138cc0a0f7f4dc0b23b18ae94538f7f(0-0). 
2021-06-18T15:08:57.7279191+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\user\Desktop\資工碩一張采庭\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T15:08:57.7532150+08:00|8|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T15:08:57.8062870+08:00|8|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T15:08:57.8583669+08:00|8|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T15:08:57.9094549+08:00|8|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T15:09:27.7656322+08:00|8|INFO|DataSync.Log|SerializationStarted. Items count: 319 
2021-06-18T15:09:27.8345761+08:00|8|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 397e6fbfbfc940b09b786205cfcee0d1(0-99). 
2021-06-18T15:09:27.8345761+08:00|8|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 397e6fbfbfc940b09b786205cfcee0d1(0-99). 
2021-06-18T15:09:49.5930705+08:00|15|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 397e6fbfbfc940b09b786205cfcee0d1(0-99). Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2021-06-18T15:09:49.5930705+08:00|15|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 397e6fbfbfc940b09b786205cfcee0d1(0-99). Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
2021-06-18T15:11:00.0621609+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\user\Desktop\資工碩一張采庭\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T15:11:00.0849770+08:00|16|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T15:11:00.1380489+08:00|16|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T15:11:00.1891369+08:00|16|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T15:11:00.2422088+08:00|16|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T15:11:30.0949142+08:00|8|INFO|DataSync.Log|SerializationStarted. Items count: 249 
2021-06-18T15:11:30.1524503+08:00|8|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: eb6f3a5b1a3c48d4b2c98b2ea5d146b6(0-99). 
2021-06-18T15:11:30.1524503+08:00|8|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: eb6f3a5b1a3c48d4b2c98b2ea5d146b6(0-99). 
2021-06-18T15:11:51.2046416+08:00|17|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: eb6f3a5b1a3c48d4b2c98b2ea5d146b6(0-99). Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2021-06-18T15:11:51.2046416+08:00|17|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: eb6f3a5b1a3c48d4b2c98b2ea5d146b6(0-99). Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
2021-06-18T15:14:00.2194974+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\user\Desktop\資工碩一張采庭\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T15:14:00.2413217+08:00|17|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T15:14:00.2943933+08:00|17|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T15:14:00.3509374+08:00|17|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T15:14:00.4025212+08:00|17|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T15:14:30.2497708+08:00|20|INFO|DataSync.Log|SerializationStarted. Items count: 131 
2021-06-18T15:14:30.2944112+08:00|20|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 989b38832ea4467292ab1291d7ea46e7(0-99). 
2021-06-18T15:14:30.2944112+08:00|20|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 989b38832ea4467292ab1291d7ea46e7(0-99). 
2021-06-18T15:15:42.2718349+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\user\Desktop\資工碩一張采庭\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T15:15:42.2971312+08:00|8|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T15:15:42.3502037+08:00|8|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T15:15:42.4007950+08:00|8|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T15:15:42.4523788+08:00|8|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T15:16:12.3070685+08:00|12|INFO|DataSync.Log|SerializationStarted. Items count: 448 
2021-06-18T15:16:12.3918843+08:00|12|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 4eaaa4104bf84dac8cf5d98f5230f4ba(0-99). 
2021-06-18T15:16:12.3918843+08:00|12|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 4eaaa4104bf84dac8cf5d98f5230f4ba(0-99). 
2021-06-18T15:25:08.6622844+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\user\Desktop\資工碩一張采庭\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T15:25:08.6920442+08:00|12|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T15:25:08.7451164+08:00|12|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T15:25:08.7991803+08:00|12|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T15:25:08.8507641+08:00|12|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T15:25:38.7009897+08:00|16|INFO|DataSync.Log|SerializationStarted. Items count: 174 
2021-06-18T15:25:38.7535655+08:00|16|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 4592c81aa658480db5ef6b980b5bf13a(0-99). 
2021-06-18T15:25:38.7535655+08:00|16|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 4592c81aa658480db5ef6b980b5bf13a(0-99). 
2021-06-18T15:25:59.8161728+08:00|19|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 4592c81aa658480db5ef6b980b5bf13a(0-99). Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2021-06-18T15:25:59.8161728+08:00|19|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 4592c81aa658480db5ef6b980b5bf13a(0-99). Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
2021-06-18T15:27:20.4329118+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\user\Desktop\資工碩一張采庭\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T15:27:20.4562237+08:00|26|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T15:27:20.5107836+08:00|26|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T15:27:20.5618719+08:00|26|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T15:27:20.6144476+08:00|26|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T15:27:50.4641772+08:00|25|INFO|DataSync.Log|SerializationStarted. Items count: 372 
2021-06-18T15:27:50.5385773+08:00|25|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: baf28ae640264230ba4d6da2ac3dbec7(0-99). 
2021-06-18T15:27:50.5435371+08:00|25|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: baf28ae640264230ba4d6da2ac3dbec7(0-99). 
2021-06-18T15:28:11.6790561+08:00|25|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: baf28ae640264230ba4d6da2ac3dbec7(0-99). Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2021-06-18T15:28:11.6810403+08:00|25|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: baf28ae640264230ba4d6da2ac3dbec7(0-99). Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
2021-06-18T15:29:33.5055373+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\user\Desktop\資工碩一張采庭\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T15:29:33.5308333+08:00|43|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T15:29:33.5858896+08:00|43|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T15:29:33.6389611+08:00|43|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T15:29:33.6925288+08:00|43|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T15:30:03.5392830+08:00|44|INFO|DataSync.Log|SerializationStarted. Items count: 258 
2021-06-18T15:30:03.5973147+08:00|44|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 38f5ce296c114022959d9c4982e7b00c(0-99). 
2021-06-18T15:30:03.5973147+08:00|44|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 38f5ce296c114022959d9c4982e7b00c(0-99). 
2021-06-18T15:30:24.6524824+08:00|42|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 38f5ce296c114022959d9c4982e7b00c(0-99). Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2021-06-18T15:30:24.6524824+08:00|42|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 38f5ce296c114022959d9c4982e7b00c(0-99). Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
2021-06-18T15:31:20.3477394+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\user\Desktop\資工碩一張采庭\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T15:31:20.3750195+08:00|58|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T15:31:20.4280916+08:00|58|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T15:31:20.4791792+08:00|58|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T15:31:20.5307634+08:00|58|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T15:31:50.3859487+08:00|65|INFO|DataSync.Log|SerializationStarted. Items count: 164 
2021-06-18T15:31:50.4325733+08:00|65|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: bee811f0247541b983321a8fb078c555(0-99). 
2021-06-18T15:31:50.4325733+08:00|65|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: bee811f0247541b983321a8fb078c555(0-99). 
2021-06-18T15:32:11.8398996+08:00|67|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: bee811f0247541b983321a8fb078c555(0-99). Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2021-06-18T15:32:11.8398996+08:00|67|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: bee811f0247541b983321a8fb078c555(0-99). Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
2021-06-18T15:34:27.8865364+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\user\Desktop\資工碩一張采庭\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T15:34:27.9108407+08:00|73|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T15:34:27.9654007+08:00|73|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T15:34:28.0164882+08:00|73|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T15:34:28.0680723+08:00|73|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T15:34:57.9227620+08:00|73|INFO|DataSync.Log|SerializationStarted. Items count: 270 
2021-06-18T15:34:57.9827777+08:00|73|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: b66d95fd4c3946b0b82db39df5b3bd19(0-99). 
2021-06-18T15:34:57.9827777+08:00|73|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: b66d95fd4c3946b0b82db39df5b3bd19(0-99). 
2021-06-18T15:35:21.2000058+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\user\Desktop\資工碩一張采庭\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T15:35:21.2257978+08:00|91|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T15:35:21.2783739+08:00|91|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T15:35:21.3299580+08:00|91|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T15:35:21.3825336+08:00|91|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T15:35:51.2347430+08:00|90|INFO|DataSync.Log|SerializationStarted. Items count: 272 
2021-06-18T15:35:51.2942636+08:00|90|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 416538b6a03743bb86b3a0f721634bcb(0-99). 
2021-06-18T15:35:51.2942636+08:00|90|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 416538b6a03743bb86b3a0f721634bcb(0-99). 
2021-06-18T15:43:17.7590424+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\user\Desktop\資工碩一張采庭\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T15:43:17.7848342+08:00|32|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T15:43:17.8384024+08:00|32|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T15:43:17.8894902+08:00|32|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T15:43:17.9440500+08:00|32|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T15:43:47.7972522+08:00|41|INFO|DataSync.Log|SerializationStarted. Items count: 408 
2021-06-18T15:43:47.8800848+08:00|41|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 2fd0cad0ec6f47b590d01b48955f56f8(0-99). 
2021-06-18T15:43:47.8800848+08:00|41|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 2fd0cad0ec6f47b590d01b48955f56f8(0-99). 
2021-06-18T15:44:08.9466593+08:00|43|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 2fd0cad0ec6f47b590d01b48955f56f8(0-99). Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2021-06-18T15:44:08.9466593+08:00|43|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 2fd0cad0ec6f47b590d01b48955f56f8(0-99). Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
2021-06-18T16:46:22.5521769+08:00|1|INFO|DataSync.Log|Storage folder: D:\unity專案\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T16:46:22.5870846+08:00|116|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T16:46:22.6429357+08:00|116|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T16:46:22.6937983+08:00|116|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T16:46:22.7456593+08:00|116|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T16:46:56.1460751+08:00|1|INFO|DataSync.Log|Storage folder: D:\unity專案\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T16:46:56.1799847+08:00|123|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T16:46:56.2353455+08:00|123|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T16:46:56.2872065+08:00|123|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T16:46:56.3390716+08:00|123|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T16:47:07.1436881+08:00|1|INFO|DataSync.Log|Storage folder: D:\unity專案\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T16:47:07.1815872+08:00|124|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T16:47:07.2349603+08:00|124|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T16:47:07.2927985+08:00|124|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T16:47:07.3441692+08:00|124|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T16:47:37.1997510+08:00|133|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2021-06-18T16:47:37.2575979+08:00|133|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 14dfb26410d045d3bb0210148f5a987f(0-0). 
2021-06-18T16:47:37.2575979+08:00|133|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 14dfb26410d045d3bb0210148f5a987f(0-0). 
2021-06-18T16:47:58.3808862+08:00|135|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 14dfb26410d045d3bb0210148f5a987f(0-0). Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2021-06-18T16:47:58.3808862+08:00|135|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 14dfb26410d045d3bb0210148f5a987f(0-0). Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
2021-06-18T16:49:14.6278512+08:00|1|INFO|DataSync.Log|Storage folder: D:\unity專案\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T16:49:14.6607348+08:00|146|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T16:49:14.7145905+08:00|146|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T16:49:14.7664518+08:00|146|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T16:49:14.8183120+08:00|146|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T16:49:44.6751839+08:00|150|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2021-06-18T16:49:44.7354725+08:00|150|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 71a7c47053034afc9aeed6c43aff33a1(0-0). 
2021-06-18T16:49:44.7384651+08:00|150|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 71a7c47053034afc9aeed6c43aff33a1(0-0). 
2021-06-18T16:56:11.1102401+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\user\Desktop\資工碩一張采庭\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T16:56:11.1340484+08:00|8|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T16:56:11.1871208+08:00|8|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T16:56:11.2382081+08:00|8|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T16:56:11.2897919+08:00|8|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T16:56:24.7482352+08:00|13|INFO|DataSync.Log|SerializationStarted. Items count: 500 
2021-06-18T16:56:24.8127153+08:00|13|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: d147850a7f884e9b8132bb6d700250a1(0-99). 
2021-06-18T16:56:24.8127153+08:00|13|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: d147850a7f884e9b8132bb6d700250a1(0-99). 
2021-06-18T16:56:45.8723466+08:00|14|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: d147850a7f884e9b8132bb6d700250a1(0-99). Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2021-06-18T16:56:45.8723466+08:00|14|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: d147850a7f884e9b8132bb6d700250a1(0-99). Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
2021-06-18T16:56:54.8419964+08:00|15|INFO|DataSync.Log|SerializationStarted. Items count: 64 
2021-06-18T16:56:54.8419964+08:00|15|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 057d116f2cfb424ea6d17b3afce12a1b(500-563). 
2021-06-18T16:56:54.8529085+08:00|15|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 057d116f2cfb424ea6d17b3afce12a1b(500-563). 
2021-06-18T16:57:16.0231477+08:00|14|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 057d116f2cfb424ea6d17b3afce12a1b(500-563). Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2021-06-18T16:57:16.0231477+08:00|14|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 057d116f2cfb424ea6d17b3afce12a1b(500-563). Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
2021-06-18T16:58:24.3197619+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\user\Desktop\資工碩一張采庭\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T16:58:24.3420821+08:00|16|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T16:58:24.3981296+08:00|16|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T16:58:24.4492174+08:00|16|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T16:58:24.5017933+08:00|16|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T16:58:54.3544993+08:00|18|INFO|DataSync.Log|SerializationStarted. Items count: 427 
2021-06-18T16:58:54.4303873+08:00|18|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: b1c631de72f641aba48717fc364707b9(0-99). 
2021-06-18T16:58:54.4323711+08:00|18|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: b1c631de72f641aba48717fc364707b9(0-99). 
2021-06-18T16:59:16.1655694+08:00|20|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: b1c631de72f641aba48717fc364707b9(0-99). Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2021-06-18T16:59:16.1655694+08:00|20|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: b1c631de72f641aba48717fc364707b9(0-99). Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
2021-06-18T17:02:26.3148103+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\user\Desktop\資工碩一張采庭\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T17:02:26.3366346+08:00|22|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T17:02:26.3921860+08:00|22|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T17:02:26.4457541+08:00|22|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T17:02:26.4968423+08:00|22|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T17:02:56.3455795+08:00|15|INFO|DataSync.Log|SerializationStarted. Items count: 374 
2021-06-18T17:02:56.4170036+08:00|15|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 2174864120cd4c318ce0091afb5a9097(0-99). 
2021-06-18T17:02:56.4170036+08:00|15|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 2174864120cd4c318ce0091afb5a9097(0-99). 
2021-06-18T17:03:17.7697704+08:00|18|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 2174864120cd4c318ce0091afb5a9097(0-99). Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2021-06-18T17:03:17.7697704+08:00|18|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 2174864120cd4c318ce0091afb5a9097(0-99). Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
2021-06-18T17:05:51.2448282+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\user\Desktop\資工碩一張采庭\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T17:05:51.2666525+08:00|15|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T17:05:51.3197241+08:00|15|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T17:05:51.3718040+08:00|15|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T17:05:51.4243804+08:00|15|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T17:06:21.2780776+08:00|14|INFO|DataSync.Log|SerializationStarted. Items count: 224 
2021-06-18T17:06:21.3366056+08:00|14|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 44f7f9ab5497466ead3165a7cf4ff17a(0-99). 
2021-06-18T17:06:21.3385896+08:00|14|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 44f7f9ab5497466ead3165a7cf4ff17a(0-99). 
2021-06-18T17:06:42.7662531+08:00|16|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 44f7f9ab5497466ead3165a7cf4ff17a(0-99). Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2021-06-18T17:06:42.7662531+08:00|16|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 44f7f9ab5497466ead3165a7cf4ff17a(0-99). Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
2021-06-18T17:14:14.9756944+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\user\Desktop\資工碩一張采庭\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T17:14:14.9995028+08:00|17|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T17:14:15.0525747+08:00|17|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T17:14:15.1046551+08:00|17|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T17:14:15.1562381+08:00|17|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T17:14:45.0109280+08:00|19|INFO|DataSync.Log|SerializationStarted. Items count: 348 
2021-06-18T17:14:45.0873120+08:00|19|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 17b3e1300b7648d29f1df58d5cc9d267(0-99). 
2021-06-18T17:14:45.0873120+08:00|19|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 17b3e1300b7648d29f1df58d5cc9d267(0-99). 
2021-06-18T17:15:06.1409913+08:00|18|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 17b3e1300b7648d29f1df58d5cc9d267(0-99). Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2021-06-18T17:15:06.1409913+08:00|18|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 17b3e1300b7648d29f1df58d5cc9d267(0-99). Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
